version: '2'
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
  redis:
    image: redis
    volumes:
        - redis_data:/data
    ports:
      - "6379:6379"
  app:
    build: .
    command:  bash -c "bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ".:/realfevrapi"
    ports:
      - "4000:3000"
    links:
      - db
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_LOG_TO_STDOUT: 'true'
      DATABASE_URL: ${DATABASE_URL}
      API_BASE_URI: ${API_BASE_URI}
  sidekiq:
    build: .
    command: bundle exec sidekiq
    links:
      - redis
      - db
    depends_on:
      - redis
      - db
    volumes:
      - ".:/realfevrapi-sidekiq"
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 'true'
      DATABASE_URL: ${DATABASE_URL}
      API_BASE_URI: ${API_BASE_URI}
volumes:
    postgres_data:
    redis_data:
